config/routes.rb
Rails.application.routes.draw do
  
  get 'subject/index'

  resources :posts do
    member do 
      post 'vote', to: 'posts#vote'
    end
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :subjects
  
  resources :users

  root 'sessions#home'

  get 'pages/home'

  get 'login' => 'sessions#login' 

  post 'login' => 'sessions#login_attempt'

  get 'logout' => 'sessions#logout'

  get 'home' => 'sessions#home'

  get 'profile' => 'sessions#profile'

  get 'setting' => 'sessions#setting'

  get 'signup' => 'users#signup'

  get 'subjects' => 'subjects#index'
  
  get 'users' => 'users#index'

  get 'statistics'=> 'sessions#statistics'

  get 'feed' => 'sessions#feed'

  get 'following' => 'users#following'

  get 'followers' => 'users#followers'

  resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
=begin
User attributes
username:   this is the username that the user goes by it can be used to log in.
       It showed be shown next to users posts and comments. S
       Should be unique
password:   personal password used to log in
email:     user's email addres it can be used to log in
=end
  has_many :posts
  has_many :comments
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  EMAIL_REGEX =  %r{[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z}i

  validates :username, presence: true, uniqueness: true, length: { in: 3..32 }
  validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX
  validates :password, confirmation: true, length: {in: 8..256}
  validates :password_confirmation, presence: true

  acts_as_voter
  has_secure_password

  def trustscore
      up_score = 0.0
      vote_score = 0.0
      self.posts.each do |post|
        up_score += post.get_upvotes.size
        vote_score += post.votes_for.size
      end
      if vote_score == 0.0
        vote_score =1.0
      end
      return up_score/vote_score * 10
    end

  def self.authenticate_with_username_or_email(username_or_email,login_password)
    if EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user.try :authenticate, login_password
      user
    else
      return nil
    end
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
  def to_s
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /signup
  def signup
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to :home, notice: 'User was successfully created.' }
      else
        format.html { render :signup }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end 
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'following'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'followers'
  end
  
private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username,:password,:password_digest,:password_confirmation, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow"%>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :email_confirmation %><br>
    <%= f.email_field :email_confirmation %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit :Signup %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow"%>
<% end %>

app/views/users/_user.html.haml
%p
  %strong Username:
  = user.username

%p
  %strong Email:
  = user.email

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/followers.html.erb
<p> Followers: </p>
<% if @users.any? %>
  <%= render @users %>
<% end %>

app/views/users/following.html.erb
<p> Following: </p>
<% if @users.any? %>
  <%= render @users %>
<% end %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Sign up', signup_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p
  <strong>Username: </strong>
  = @user.username

%p
  <strong>Email: </strong>
  = @user.email

%h1 Welcome #{@user.to_s}, to your profile page!
%p Here, you'll be allowed to view, edit, and destroy your posts
%h2 Some stats for you
%p
  Total number of your posts : #{@user.posts.count}
%p
  Democracy level (votes given) : #{@user.votes.size}
%p
  Trust score : #{@user.trustscore}

%table
  %thead
    %tr
      %th Score
      %th Title
      %th Contents
      %th Author
      %th{colspan: "3"}
  %tbody
    - @user.posts.each do |post|
      %tr
        %td= post.score
        %td= post.title
        %td= post.contents
        %td= post.user.to_s
        %td= link_to 'Open', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

= render 'follow_form' if current_user

%h3 Posts (#{@user.posts.count})
= render @user.posts

= link_to 'Edit', edit_user_path(@user)
= link_to 'Feed', feed_path

app/views/users/signup.html.erb
<h1>Sign up today!</h1>


<%= render 'signup_form' %>

<%= link_to 'Back', home_path %>