config/routes.rb
Rails.application.routes.draw do
  
  get 'subject/index'

  resources :posts do
    member do 
      post 'vote', to: 'posts#vote'
    end
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :subjects
  
  resources :users

  root 'sessions#home'

  get 'pages/home'

  get 'login' => 'sessions#login' 

  post 'login' => 'sessions#login_attempt'

  get 'logout' => 'sessions#logout'

  get 'home' => 'sessions#home'

  get 'profile' => 'sessions#profile'

  get 'setting' => 'sessions#setting'

  get 'signup' => 'users#signup'

  get 'subjects' => 'subjects#index'
  
  get 'users' => 'users#index'

  get 'statistics'=> 'sessions#statistics'

  get 'feed' => 'sessions#feed'

  get 'following' => 'users#following'

  get 'followers' => 'users#followers'

  resources :relationships,       only: [:create, :destroy]

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, presence: true, uniqueness: true
  validates :desc, presence: true
  
  def to_param
    name
  end
  
  def self.where_not_includes post
    Subject.find_by_sql [<<-SQL, post.id]
      SELECT * FROM subjects
      WHERE NOT EXISTS (
        SELECT * FROM posts_subjects
        WHERE subject_id = subjects.id
        AND   post_id = ?
      )
    SQL
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:new, :show, :edit, :update, :destroy]
  
  def index
    @subjects = Subject.all
  end
  
  def show
    @post = Post.new
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def set_subject
    @subject = Subject.find_by_name params[:id]
  end

  def subject_params
    params.require(:subject).permit(:name, :desc)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
= form_for @subject do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :desc
    = f.text_area :desc
  .actions
    = f.submit
  - if @subject.errors.any?
    #error_explaination
      %h2 #{pluralize @subject.errors.count, 'error'} prohibited this subject from being saved:
      %ul
        - @subject.errors.full_messages.each do |message|
          %li= message

app/views/subjects/index.html.haml
%h1 Subjects
%ul
  - if Subject.count == 0
    %li= 'No Subjects to Display.'
  - @subjects.each do |s|
    %li= link_to s.name, s
  %p= link_to 'New Subject', new_subject_path
  %p= link_to 'Home', home_path

app/views/subjects/new.html.haml
%h1= 'New Subject'

= render 'form'

= link_to 'Back', subjects_path

app/views/subjects/show.html.haml
- @title = @subject.name
%p= @subject.desc

#posts
  = render @subject.posts.order_by_score
  - if current_user
    = form_for Post.new do |f|
      = f.hidden_field :subject_ids, value: @subject.id
      .field
        = f.label :title
        = f.text_field :title
      .field
        = f.label :contents
        = f.text_area :contents
      .actions
        = f.submit
      - if @post.errors.any?
        #error_explaination
          %h2 #{pluralize @post.errors.count, 'error'} prohibited this subject from being saved:
          %ul
            - @post.errors.full_messages.each do |message|
              %li= message
  - else
    = link_to "Login to Post", login_path