config/routes.rb
Rails.application.routes.draw do
  
  get 'subject/index'

  resources :posts do
    member do 
      post 'vote', to: 'posts#vote'
    end
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :subjects
  
  resources :users

  root 'sessions#home'

  get 'pages/home'

  get 'login' => 'sessions#login' 

  post 'login' => 'sessions#login_attempt'

  get 'logout' => 'sessions#logout'

  get 'home' => 'sessions#home'

  get 'profile' => 'sessions#profile'

  get 'setting' => 'sessions#setting'

  get 'signup' => 'users#signup'

  get 'subjects' => 'subjects#index'
  
  get 'users' => 'users#index'

  get 'statistics'=> 'sessions#statistics'

  get 'feed' => 'sessions#feed'

  get 'following' => 'users#following'

  get 'followers' => 'users#followers'

  resources :relationships,       only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :subjects
  has_many :comments, dependent: :destroy
  validates :title, :contents, presence: true

  acts_as_votable

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
  
  def subject_ids_add= ids
    update subject_ids: subject_ids + [*ids]
  end
  
  def vote_by_user user
    return 0 unless user
    vote = votes_for.where(voter: user).take
    pp vote
    return 0 unless vote
    vote.vote_flag ? vote.vote_weight : -vote.vote_weight
  end
  
  def self.order_by_score
    order <<-SQL
      (SELECT
        COALESCE(
          SUM(CASE WHEN vote_flag THEN vote_weight ELSE -VOTE_WEIGHT END),
          0)
      FROM votes
      WHERE votable_id = posts.id
      AND votable_type = 'Post') DESC
    SQL
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        unless @post.subjects.empty?
          format.html { redirect_to @post.subjects.first, notice: 'Post was successfully created.' }
        else
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user == current_user
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was not destroyed. You do not own this post' }
      end
    end
  end

  def vote
    w = params.require(:weight).to_i
    case
    when w > 0
      pp "UP", w, @post, current_user
      @post.upvote_by current_user
    when w < 0
      pp "DOWN", w, @post, current_user
      @post.downvote_by current_user
    else
      pp "ZERO", w, @post, current_user
      @post.unvote_by current_user
    end
    render nothing: true
  end

  private
  def set_post
    @post = Post.find(params.require(:id))
  end

  def post_params
    params.require(:post).permit :title,
                                 :contents,
                                 :author_id,
                                 :subject_ids,
                                 :subject_ids_add
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="field">
    <%= f.label :making_post_as_user %><br>
    <%= f.label current_user.username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.haml
.post
  .self
    %h2.title
      = post.title
      .votes
        - vote = post.vote_by_user current_user
        %form.up{'data-target': vote_post_path(post), class: vote > 0 && :active}
          %button.icon thumb_up
        %span.score= post.score
        %form.down{'data-target': vote_post_path(post), class: vote < 0 && :active}
          %button.icon thumb_down
    .meta
      posted
      \ #{link_to "#{time_ago_in_words post.created_at} ago", post}
      \ by
      \ #{link_to post.user, post.user}
    .contents!= post.contents

  .comments
    = render post.comments
    .commentish.add-comment
      - if current_user
        = form_for [post, post.comments.build] do |f|
          = f.text_field :contents
          = f.submit 'Comment'
      - else
        = link_to "Login to Comment", login_path

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
%h1 Listing Posts
= render @posts.order_by_score

= link_to 'New Post', new_post_path
= link_to 'Home', home_path

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.haml
- @title = @post.title

= render @post

%h2 Add this post to:
%ul
  - Subject.where_not_includes(@post).each do |subject|
    %li
      = form_for @post, method: :patch do |f|
        = f.hidden_field :subject_ids_add, value: subject.id
        = f.submit subject.name

%h2 This post is in:
%ul
  - @post.subjects.each do |subject|
    %li= link_to subject.name, subject