config/routes.rb
Rails.application.routes.draw do
  
  get 'subject/index'

  resources :posts do
    member do 
      post 'vote', to: 'posts#vote'
    end
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :subjects
  
  resources :users

  root 'sessions#home'

  get 'pages/home'

  get 'login' => 'sessions#login' 

  post 'login' => 'sessions#login_attempt'

  get 'logout' => 'sessions#logout'

  get 'home' => 'sessions#home'

  get 'profile' => 'sessions#profile'

  get 'setting' => 'sessions#setting'

  get 'signup' => 'users#signup'

  get 'subjects' => 'subjects#index'
  
  get 'users' => 'users#index'

  get 'statistics'=> 'sessions#statistics'

  get 'feed' => 'sessions#feed'

  get 'following' => 'users#following'

  get 'followers' => 'users#followers'

  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/application.html.haml
!!!html
%html
  %head
    %title Social Wiki
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = stylesheet_link_tag 'application', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
    = yield :head

  %body
    = javascript_include_tag javascript_path params[:controller]
    = stylesheet_link_tag stylesheet_path params[:controller]
    %header
      = link_to "Social Wiki", "/", {id: 'logo'}
      %h1.flex= @title
      - if current_user
        = link_to current_user, current_user
        = link_to 'Logout', logout_path
      - else
        = link_to "Log in", login_path
        = link_to "Sign up", signup_path
      
      = link_to "Statistics", statistics_path  
    %p#notice= notice
    
    #body
      = yield